# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build Cars App
  jobs:
  - job: Build
    displayName: Build job
    pool:
      vmImage: 'windows-latest'
    variables:
      solution: '**/*.sln'
      buildPlatform: 'x86'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: DotNetCoreCLI@2
      displayName: 'Building Projects'
      inputs:
        command: 'build'
        projects: '$(Build.SourcesDirectory)/**/*.sln'
        arguments: '--configuration $(buildConfiguration)'
    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: CopyFiles@2
      inputs:
        contents: '**\$(BuildConfiguration)\**\?(*.exe|*.dll|*.pdb)' 
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: CarProjectArtifacts
- stage: Dev
  displayName: Deploy to the dev environment
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploy to the DEV environment
- stage: Test
  displayName: Deploy to the test environment
  dependsOn: Dev
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: test
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploy to the TEST environment
- stage: Staging
  displayName: Deploy to the staging environment
  dependsOn: Test
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'windows-latest'
    environment: staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploy to the STAGING environment
